---
- name: Apply STIG Remediation Scripts
  hosts: all
  gather_facts: false
  vars_files:
    - ../../vaults/rhel8_vault.yml
  vars:
    ansible_tmp_dir: /var/ansible_tmp
  roles:
    - rhel8  # <-- Change to switch 