# roles/rhel8/tasks/main.yml
---
- name: Create a temporary directory for STIG scripts
  ansible.builtin.tempfile:
    state: directory
    prefix: ansible_stigs_
  register: stig_temp_dir
  tags: always

- name: Copy all STIG scripts for RHEL8 to the remote host
  ansible.builtin.copy:
    # Copy the entire RHEL8 directory, which contains all CAT categories
    src: "OS/RHEL8/"
    dest: "{{ stig_temp_dir.path }}/"
    mode: '0755'
  tags: always

- name: Execute STIG remediation scripts
  become: true # Use sudo
  ansible.builtin.shell:
    # Find the script inside the copied directory structure and execute it.
    cmd: "find {{ stig_temp_dir.path }} -name '{{ item }}' -exec bash {} \\;"
    warn: false
  loop: "{{ stig_scripts }}"
  register: script_output
  changed_when: script_output.rc != 0
  tags:
    - "stig_remediation" # The fix: a static, generic tag.

- name: Clean up the temporary directory
  ansible.builtin.file:
    path: "{{ stig_temp_dir.path }}"
    state: absent
  when: stig_temp_dir.path is defined
  tags: always