# roles/rhel8/tasks/main.yml
---
- name: Create a temporary directory for STIG scripts
  ansible.builtin.tempfile:
    state: directory
    prefix: ansible_stigs_
  register: stig_temp_dir
  tags: always

- name: Sync all STIG scripts for RHEL8 to the remote host
  ansible.builtin.synchronize:
    src: "OS/RHEL8/"
    dest: "{{ stig_temp_dir.path }}/"
    mode: push
    archive: yes
  delegate_to: "{{ inventory_hostname }}"
  tags: always

- name: Execute STIG remediation scripts
  become: true
  ansible.builtin.shell:
    cmd: "find {{ stig_temp_dir.path }} -name '{{ item }}' -exec bash {} \\;"
    warn: false
  loop: "{{ stig_scripts }}"
  tags:
    - "stig_remediation"

- name: Clean up the temporary directory
  ansible.builtin.file:
    path: "{{ stig_temp_dir.path }}"
    state: absent
  when: stig_temp_dir.path is defined
  tags: always